# Generated by Django 5.0.4 on 2024-04-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_player_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('fullname', models.CharField(max_length=40)),
                ('nickname', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
