# Generated by Django 5.0.4 on 2024-04-29 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_winners_alter_player_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Winners',
            new_name='Winner',
        ),
    ]
