# Generated by Django 5.0.4 on 2024-04-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_winner_nickname_alter_winner_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('nickname', models.CharField(max_length=20)),
                ('opponent_nickname', models.CharField(max_length=20)),
            ],
        ),
    ]
