# Generated by Django 5.0.4 on 2024-04-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_looser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('fullname', models.CharField(max_length=40)),
                ('nickname', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=5)),
            ],
        ),
    ]
